### ISSUE TITLE
GeoJSON type is not standard compliant

### ISSUE THREAD

**Issue by wyvernzora** [rh389/dynamodb-geo.js#12]
More specifically, in [this line](https://github.com/rh389/dynamodb-geo.js/blob/68f0becdca8909b875664b6fa73c2d5da24f084d/src/dynamodb/DynamoDBManager.ts#L123) the type of GeoJSON object is set to `POINT` instead of `Point`, which some GeoJSON manipulation libraries do not recognize (e.g. turf).

I would suggest that instead of having a `[lat,lon]` order option, we should have an option to turn on  GeoJSON standard compliance vs recreating the logic of original dynamodb-geo.

I will be happy to create a PR in a few days.

**Comment by rh389** [comment]
Yes, you're right. If you would like to put in a PR to do as you suggest it'd be most welcome.
