### ISSUE TITLE
queryRadius returns correct response on my local environment but gives "Internal server error" when I send request using postman

### ISSUE THREAD

**Issue by lantikchi** [rh389/dynamodb-geo.js#17]
Hi,
I have a API Gateway with a GET - /getbylocation method which returns all the data within a radius of the given point. The following is my code: I get the radius by calculating the distance between two given points (from/to latitude/longitude).

```
module.exports = (req, res, next) => {

  var fromLatitude= parseFloat(req.query.fromLatitude);
  var toLatitude= parseFloat(req.query.toLatitude);
  var fromLongitude= parseFloat(req.query.fromLongitude);
  var toLongitude= parseFloat(req.query.toLongitude);

   const ddb = new AWS.DynamoDB(awsConfig ); 
   const config = new ddbGeo.GeoDataManagerConfiguration(ddb,'activities');
   const activityManager  = new ddbGeo.GeoDataManager(config);

  // Find the distance between from/to locations 
  var radius = geolib.getDistance({latitude: fromLatitude, longitude: fromLongitude }, {latitude: toLatitude, longitude: toLongitude});

   activityManager.queryRadius({
            RadiusInMeter: radius,
            CenterPoint: {
                latitude: fromLatitude,
                longitude: fromLongitude
            }
        })

        .then(result => {
        winston.info(`Read ${result.length} labels from ${req.config.ACTIVITIES_TABLE_NAME}`);
        res.json(result);
        next();
  })    .catch(err => next(error.InternalError(err)));


 }
```

When I send a request to the API gateway,  I get the correct response with the correct data from the dynamodb table. 

`const event = {
  "httpMethod": "GET",
  "headers": {
    "Content-Type": "application/json"
  },
  "path": "/getbylocation",
  "resource": "/getbylocation",
  "stageVariables": { lbfunc: "services" },
  "queryStringParameters": {
    "fromLatitude":"47.6062",
    "fromLongitude":"122.3321",
    "toLatitude":"49.2827",
    "toLongitude":"123.1207"
  }
};`

However, after deploying this on AWS, and sending a request using postman I get no response. 
```
{
    "message": "Internal server error"
}
```
below is the error I get on the API log:

![image](https://user-images.githubusercontent.com/8550118/36756196-329c55c2-1bc3-11e8-84be-172e10267832.png)

I'm really not sure what I'm doing wrong, I'd really appreciate it if you could take a look and advise please.

Thank you

**Comment by rh389** [comment]
The API log shows that your request is timing out because it's taking longer than 3 seconds. That might be because it needs more time, or it might be because your function doesn't end/return properly.

Is that a standalone lambda function you've posted or part of some larger thing (it looks like express?). In any case it doesn't look right to me that you're calling `res.json()` _and_ `next()`. Normally you only use `next()` when you're writing middleware that doesn't handle the response.

**Comment by lantikchi** [comment]
Thank you for your reply. I increased the time out to 25 and I get the correct response now.
Really appreciate it .
