### ISSUE TITLE
Erratic "Requested resource not found" errors

### ISSUE THREAD

**Issue by bonmedi** [rh389/dynamodb-geo.js#21]
I am receiving in my setup erratic `Requested resource not found` errors and I was not able to track down the root cause. To isolate the problem I simplified everything in the setup but still the errors. 

Here the setup:

**Table (~2200 items):**
![bildschirmfoto 2018-04-20 um 23 31 15](https://user-images.githubusercontent.com/35409168/39074755-fafe3a6e-44f2-11e8-8900-78ca63befbee.png)

**The code**
```const region = 'eu-west-1';
AWS.config.update({ region });
const config = new ddbGeo.GeoDataManagerConfiguration(new AWS.DynamoDB(), DDB_GEO_TABLENAME);
config.hashKeyLength = 2;
config.consistentRead = false;
const geoMng = new ddbGeo.GeoDataManager(config);
const ddbClient = new AWS.DynamoDB.DocumentClient();

geoMng.queryRadius({
   RadiusInMeter: 500000,
   CenterPoint: {
     latitude: 53.5510846,
     longitude: 9.993681899999956,
   },
})
.then((geoData) => {
 console.log(new Date() + " :: count="+geoData.length);
 });
```

**The normal output**
```
Fri Apr 20 2018 23:25:20 GMT+0200 (CEST) :: count=1744
Fri Apr 20 2018 23:25:24 GMT+0200 (CEST) :: count=1744
Fri Apr 20 2018 23:25:28 GMT+0200 (CEST) :: count=1744
```

**The error**
`(node:84464) ResourceNotFoundException: Requested resource not found
    at Request.extractError (/node_modules/aws-sdk/lib/protocol/json.js:47:27)
    at Request.callListeners (/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/node_modules/aws-sdk/lib/sequential_executor.js:115:18)`

**The result**
I run the snipped for some time calling it couple of seconds:

![bildschirmfoto 2018-04-20 um 23 43 06](https://user-images.githubusercontent.com/35409168/39075184-cb49f57c-44f4-11e8-8ea8-d0d23581ba11.png)

Anyone with an idea for the cause or a good hint how to track this nasty thing down? Thanks!

**Comment by rh389** [comment]
Did you ever get to the bottom of this? It sounds like a problem on the AWS side to me, it’s not something I’ve experienced.

**Comment by bonmedi** [comment]
Not really. It just disappeared once I moved from eu-west-1 to eu-central-1 for other reasons. I would think the DDB table was internally somehow screwed.
