### ISSUE TITLE
Package JSON Installs @types/long, but the code requires long

### ISSUE THREAD

**Issue by paulcruse-syn** [rh389/dynamodb-geo.js#54]
Your package has an error when you try t use it with the [serverless framework](https://www.serverless.com/).

In your package.json you require `"@types/long": ">=3",`

```json
{
  "name": "dynamodb-geo",
  "version": "0.4.0",
  "description": "A javascript port of awslabs/dynamodb-geo, for dynamodb geospatial querying",
  "scripts": {
    "prepublish": "tsc -d",
    "clean": "rm -rf dist",
    "build": "tsc -d",
    "test": "mocha --require ts-node/register test/**/*.ts"
  },
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "repository": "rh389/dynamodb-geo.js",
  "author": "Rob Hogan <github@rhogan.net>",
  "license": "Apache-2.0",
  "dependencies": {
    "@types/decimal.js": "^0.0.30",
    "@types/long": ">=3",
    "nodes2ts": "^1.1.10"
  },
  "devDependencies": {
    "@types/chai": "^4.0.0",
    "@types/mocha": "^2.2.41",
    "@types/node": "^7.0.27",
    "aws-sdk": "^2.248.1",
    "chai": "^4.0.1",
    "mocha": "^3.3.0",
    "ts-node": "^3.0.2",
    "typescript": "^2.3.4"
  },
  "peerDependencies": {
    "aws-sdk": "^2.176.0"
  }
}
```

But in your code import just long `import * as Long from 'long';` (https://github.com/rh389/dynamodb-geo.js/blob/master/src/model/GeohashRange.ts#L3)... which isn't the same as `"@types/long": ">=3",`.

So when serverless packages up your module, it remove the `long` package because it isn't part of the dependencies. 

The solution is to just include `long` in our project, but figure you might want to know how your package is being used and the errors therein.

**Comment by zsyphon** [comment]
@paulcruse-syn Were you ever able to find a solution for this problem?

**Comment by paulcruse-syn** [comment]
The solution is to simply include the long package in your list of dependencies. 

npm install long
